$("Document").ready(function(){
	$("p1").css("color","blue");
	$("h1").css("backgroundColor","green");
	$("p4").hide(3000);
	$(":text").css("color",'Red');
	$(":text").css("backgroundColor",'blue');
	$(":submit").css("color",'blue');
$("[href]").css("backgroundColor","blue");
$("[href]").css("color","white");
});